/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import koneksi.New_ConnectDB;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class Dashboard extends javax.swing.JFrame {
    private Connection conn = new New_ConnectDB().connect();
    private DefaultTableModel tabmode;
    JasperReport jasrep;
    JasperPrint jaspri;
    JasperDesign jasdes;

    /**
     * Creates new form Dashboard
     */
    boolean a = true;
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(this);
        //hideshow(MainMenu,a, btn_Back);
        animated();
        auto_number();
        count();
        total_kwh();;
        total_income();
        //MainFrame.setVisible(false);
    }
    
    protected void count(){
        //int row = tabmode.getRowCount();
        //for (int i = 0;i<row;i++) {
        tabmode = new DefaultTableModel();    
        String sql = "select * from owner_detail_apart";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String [] data={hasil.getString(1),hasil.getString(2),hasil.getString(3)};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        int b=tabmode.getRowCount();
        tf_units.setText(""+b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        IkonWindow = new javax.swing.JPanel();
        btn_Min = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_Close = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_Max = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MainMenu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        line = new javax.swing.JPanel();
        jp_setting = new javax.swing.JPanel();
        btn_Setting = new javax.swing.JLabel();
        jp_back = new javax.swing.JPanel();
        btn_Back = new javax.swing.JLabel();
        line1 = new javax.swing.JPanel();
        MenuHide = new javax.swing.JPanel();
        MenuHide_Template = new javax.swing.JPanel();
        Template_1 = new javax.swing.JPanel();
        btn_unit = new javax.swing.JLabel();
        Template_2 = new javax.swing.JPanel();
        btn_Payment = new javax.swing.JLabel();
        Template_3 = new javax.swing.JPanel();
        btn_Result = new javax.swing.JLabel();
        branding = new javax.swing.JLabel();
        detail = new javax.swing.JLabel();
        branding1 = new javax.swing.JLabel();
        bg_MainMenu = new javax.swing.JLabel();
        MainFrame = new javax.swing.JPanel();
        MainFrame_Home = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        layout1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        layout2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jp_Detail_1 = new javax.swing.JPanel();
        jp_Detail_2 = new javax.swing.JPanel();
        detailConcept = new javax.swing.JLabel();
        bg_MainFrame_Home = new javax.swing.JLabel();
        Transaction_Apart = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cb_Tower = new javax.swing.JComboBox<>();
        cb_BadType = new javax.swing.JComboBox<>();
        cb_UnitStyle = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_alamat = new javax.swing.JTextArea();
        tf_nohp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bg_layout = new javax.swing.JLabel();
        bg_Transaction = new javax.swing.JLabel();
        Payment_System = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tf_id1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_nama1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_nohp1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_KWH = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tf_total = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_used = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        bg_layout1 = new javax.swing.JLabel();
        bg_Transaction1 = new javax.swing.JLabel();
        Result = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_kwh_usage = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_income = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_units = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        bg_layout2 = new javax.swing.JLabel();
        bg_Transaction2 = new javax.swing.JLabel();
        tf_income_tumbal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(56, 94, 245));
        Header.setPreferredSize(new java.awt.Dimension(1071, 45));
        Header.setLayout(new java.awt.BorderLayout());

        IkonWindow.setBackground(new java.awt.Color(56, 94, 245));
        IkonWindow.setPreferredSize(new java.awt.Dimension(135, 45));
        IkonWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Min.setBackground(new java.awt.Color(56, 94, 245));
        btn_Min.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Min.add(jLabel3, java.awt.BorderLayout.CENTER);

        IkonWindow.add(btn_Min, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 45, 45));

        btn_Close.setBackground(new java.awt.Color(56, 94, 245));
        btn_Close.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/delete_32px.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        btn_Close.add(jLabel4, java.awt.BorderLayout.CENTER);

        IkonWindow.add(btn_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 45, 45));

        btn_Max.setBackground(new java.awt.Color(56, 94, 245));
        btn_Max.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/full_screen_32px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        btn_Max.add(jLabel2, java.awt.BorderLayout.CENTER);

        IkonWindow.add(btn_Max, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, 45, 45));

        Header.add(IkonWindow, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        MainMenu.setBackground(new java.awt.Color(149, 223, 237));
        MainMenu.setPreferredSize(new java.awt.Dimension(270, 514));
        MainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuIcon.setBackground(new java.awt.Color(56, 94, 245));
        MenuIcon.setPreferredSize(new java.awt.Dimension(45, 514));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        line.setBackground(new java.awt.Color(56, 94, 245));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        MenuIcon.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 45, 5));

        jp_setting.setBackground(new java.awt.Color(56, 94, 245));

        btn_Setting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/lock-icon_white_32px.png"))); // NOI18N
        btn_Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SettingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jp_settingLayout = new javax.swing.GroupLayout(jp_setting);
        jp_setting.setLayout(jp_settingLayout);
        jp_settingLayout.setHorizontalGroup(
            jp_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_settingLayout.setVerticalGroup(
            jp_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuIcon.add(jp_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 45, 45));

        jp_back.setBackground(new java.awt.Color(56, 94, 245));

        btn_Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/back_32px.png"))); // NOI18N
        btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jp_backLayout = new javax.swing.GroupLayout(jp_back);
        jp_back.setLayout(jp_backLayout);
        jp_backLayout.setHorizontalGroup(
            jp_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_backLayout.setVerticalGroup(
            jp_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuIcon.add(jp_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 45, 45));

        line1.setBackground(new java.awt.Color(56, 94, 245));

        javax.swing.GroupLayout line1Layout = new javax.swing.GroupLayout(line1);
        line1.setLayout(line1Layout);
        line1Layout.setHorizontalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        line1Layout.setVerticalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        MenuIcon.add(line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 45, 5));

        MainMenu.add(MenuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MenuHide.setBackground(new java.awt.Color(57, 121, 255));
        MenuHide.setLayout(new java.awt.BorderLayout());

        MenuHide_Template.setBackground(new java.awt.Color(57, 121, 255));
        MenuHide_Template.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuHide_TemplateMouseEntered(evt);
            }
        });

        Template_1.setBackground(new java.awt.Color(204, 204, 204));
        Template_1.setPreferredSize(new java.awt.Dimension(116, 35));
        Template_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Template_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Template_1MouseExited(evt);
            }
        });

        btn_unit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_unit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/City-Hotel-icon.png"))); // NOI18N
        btn_unit.setText("Pembelian Unit");
        btn_unit.setPreferredSize(new java.awt.Dimension(106, 32));
        btn_unit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_unitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_unitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_unitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Template_1Layout = new javax.swing.GroupLayout(Template_1);
        Template_1.setLayout(Template_1Layout);
        Template_1Layout.setHorizontalGroup(
            Template_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Template_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_unit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Template_1Layout.setVerticalGroup(
            Template_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_unit, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        Template_2.setBackground(new java.awt.Color(204, 204, 204));
        Template_2.setPreferredSize(new java.awt.Dimension(205, 35));

        btn_Payment.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_Payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/Electricity-icon.png"))); // NOI18N
        btn_Payment.setText("Pembayaran Listrik");
        btn_Payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PaymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_PaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_PaymentMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Template_2Layout = new javax.swing.GroupLayout(Template_2);
        Template_2.setLayout(Template_2Layout);
        Template_2Layout.setHorizontalGroup(
            Template_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Template_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Payment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Template_2Layout.setVerticalGroup(
            Template_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Payment, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        Template_3.setBackground(new java.awt.Color(204, 204, 204));
        Template_3.setPreferredSize(new java.awt.Dimension(205, 35));

        btn_Result.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_Result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/File-Graph-icon.png"))); // NOI18N
        btn_Result.setText("Laporan");
        btn_Result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ResultMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ResultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ResultMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Template_3Layout = new javax.swing.GroupLayout(Template_3);
        Template_3.setLayout(Template_3Layout);
        Template_3Layout.setHorizontalGroup(
            Template_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Template_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Template_3Layout.setVerticalGroup(
            Template_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Result, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        branding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/logo-white.png"))); // NOI18N

        detail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        detail.setForeground(new java.awt.Color(255, 255, 255));
        detail.setText("Reminiscent of Waterfall from the Sky");

        javax.swing.GroupLayout MenuHide_TemplateLayout = new javax.swing.GroupLayout(MenuHide_Template);
        MenuHide_Template.setLayout(MenuHide_TemplateLayout);
        MenuHide_TemplateLayout.setHorizontalGroup(
            MenuHide_TemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHide_TemplateLayout.createSequentialGroup()
                .addGroup(MenuHide_TemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuHide_TemplateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuHide_TemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Template_1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(Template_2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(Template_3, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addGroup(MenuHide_TemplateLayout.createSequentialGroup()
                                .addComponent(detail)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(MenuHide_TemplateLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(branding, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MenuHide_TemplateLayout.setVerticalGroup(
            MenuHide_TemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHide_TemplateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(branding, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detail)
                .addGap(18, 18, 18)
                .addComponent(Template_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Template_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Template_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        MenuHide.add(MenuHide_Template, java.awt.BorderLayout.CENTER);

        MainMenu.add(MenuHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, 225, 514));

        branding1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/logo-white.png"))); // NOI18N
        MainMenu.add(branding1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 6, 123, 50));

        bg_MainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/view_transparant.png"))); // NOI18N
        MainMenu.add(bg_MainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1071, 514));

        getContentPane().add(MainMenu, java.awt.BorderLayout.LINE_START);

        MainFrame.setBackground(new java.awt.Color(149, 223, 237));
        MainFrame.setLayout(new java.awt.CardLayout());

        MainFrame_Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Reminiscent of Waterfall from the Sky");
        MainFrame_Home.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 79, 402, -1));

        layout1.setBackground(new java.awt.Color(222, 222, 222));
        layout1.setPreferredSize(new java.awt.Dimension(200, 200));

        jPanel1.setBackground(new java.awt.Color(222, 222, 222));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Picture1_small.jpg"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout1Layout = new javax.swing.GroupLayout(layout1);
        layout1.setLayout(layout1Layout);
        layout1Layout.setHorizontalGroup(
            layout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout1Layout.setVerticalGroup(
            layout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainFrame_Home.add(layout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 330, 210));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("OUR CONSEPT");
        MainFrame_Home.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 43, 199, -1));

        layout2.setBackground(new java.awt.Color(222, 222, 222));
        layout2.setPreferredSize(new java.awt.Dimension(200, 200));

        jPanel2.setBackground(new java.awt.Color(222, 222, 222));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Picture2_small.jpg"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 199, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout2Layout = new javax.swing.GroupLayout(layout2);
        layout2.setLayout(layout2Layout);
        layout2Layout.setHorizontalGroup(
            layout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout2Layout.setVerticalGroup(
            layout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainFrame_Home.add(layout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 330, 210));

        jp_Detail_1.setBackground(new java.awt.Color(222, 222, 222));

        jp_Detail_2.setBackground(new java.awt.Color(222, 222, 222));

        javax.swing.GroupLayout jp_Detail_2Layout = new javax.swing.GroupLayout(jp_Detail_2);
        jp_Detail_2.setLayout(jp_Detail_2Layout);
        jp_Detail_2Layout.setHorizontalGroup(
            jp_Detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_Detail_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailConcept, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jp_Detail_2Layout.setVerticalGroup(
            jp_Detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_Detail_2Layout.createSequentialGroup()
                .addComponent(detailConcept, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_Detail_1Layout = new javax.swing.GroupLayout(jp_Detail_1);
        jp_Detail_1.setLayout(jp_Detail_1Layout);
        jp_Detail_1Layout.setHorizontalGroup(
            jp_Detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_Detail_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Detail_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_Detail_1Layout.setVerticalGroup(
            jp_Detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_Detail_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Detail_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainFrame_Home.add(jp_Detail_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 393, 720, 40));

        bg_MainFrame_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/view_transparant.png"))); // NOI18N
        MainFrame_Home.add(bg_MainFrame_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 1071, 514));

        MainFrame.add(MainFrame_Home, "card5");

        Transaction_Apart.setBackground(new java.awt.Color(149, 223, 237));
        Transaction_Apart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setText("Address");
        Transaction_Apart.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setText("Room Plan");
        Transaction_Apart.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setText("Unit Style");
        Transaction_Apart.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setText("Tower");
        Transaction_Apart.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setText("Bad Type");
        Transaction_Apart.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        cb_Tower.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "North Tower", "South Tower" }));
        Transaction_Apart.add(cb_Tower, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 110, 25));

        cb_BadType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Bed", "2 Bed", "3 Bed" }));
        Transaction_Apart.add(cb_BadType, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 110, 25));

        cb_UnitStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Living Style", "Luxurious Style", "Japanese Style" }));
        Transaction_Apart.add(cb_UnitStyle, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 150, 25));

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel17.setText("No Handphone");
        Transaction_Apart.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setText("Name");
        Transaction_Apart.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        tf_nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Transaction_Apart.add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 260, 25));

        ta_alamat.setColumns(20);
        ta_alamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ta_alamat.setRows(5);
        jScrollPane1.setViewportView(ta_alamat);

        Transaction_Apart.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 260, 100));

        tf_nohp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Transaction_Apart.add(tf_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 160, 25));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel18.setText("Id Number  ");
        Transaction_Apart.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        tf_id.setEditable(false);
        tf_id.setBackground(new java.awt.Color(255, 255, 255));
        Transaction_Apart.add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 90, 25));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/Save-icon.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Transaction_Apart.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        bg_layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/bg_trans.png"))); // NOI18N
        Transaction_Apart.add(bg_layout, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 560, 440));

        bg_Transaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/view_transparant.png"))); // NOI18N
        bg_Transaction.setMaximumSize(new java.awt.Dimension(801, 514));
        bg_Transaction.setMinimumSize(new java.awt.Dimension(801, 514));
        Transaction_Apart.add(bg_Transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 1070, 513));

        MainFrame.add(Transaction_Apart, "card2");

        Payment_System.setBackground(new java.awt.Color(149, 223, 237));
        Payment_System.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel19.setText("Id Number  ");
        Payment_System.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        tf_id1.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        tf_id1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_id1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_id1KeyReleased(evt);
            }
        });
        Payment_System.add(tf_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 220, 25));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel20.setText("Name");
        Payment_System.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 165, -1, -1));

        tf_nama1.setEditable(false);
        tf_nama1.setBackground(new java.awt.Color(255, 255, 255));
        tf_nama1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Payment_System.add(tf_nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 165, 220, 25));

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel21.setText("Last Month (KWH)");
        Payment_System.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        tf_nohp1.setEditable(false);
        tf_nohp1.setBackground(new java.awt.Color(255, 255, 255));
        tf_nohp1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Payment_System.add(tf_nohp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 220, 25));

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel22.setText("No Handphone");
        Payment_System.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        tf_KWH.setEditable(false);
        tf_KWH.setBackground(new java.awt.Color(255, 255, 255));
        tf_KWH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Payment_System.add(tf_KWH, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 235, 100, 25));

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel23.setText("This");
        Payment_System.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        tf_total.setEditable(false);
        tf_total.setBackground(new java.awt.Color(255, 255, 255));
        tf_total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Payment_System.add(tf_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 120, 25));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel24.setText("Total");
        Payment_System.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        tf_used.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_used.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usedActionPerformed(evt);
            }
        });
        tf_used.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_usedKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_usedKeyReleased(evt);
            }
        });
        Payment_System.add(tf_used, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 235, 70, 25));

        jButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/Finance-Cash-Receiving-icon.png"))); // NOI18N
        jButton2.setText("Payout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Payment_System.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        bg_layout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/bg_trans.png"))); // NOI18N
        Payment_System.add(bg_layout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 620, 440));

        bg_Transaction1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/view_transparant.png"))); // NOI18N
        bg_Transaction1.setMaximumSize(new java.awt.Dimension(801, 514));
        bg_Transaction1.setMinimumSize(new java.awt.Dimension(801, 514));
        Payment_System.add(bg_Transaction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 1070, 513));

        MainFrame.add(Payment_System, "card3");

        Result.setBackground(new java.awt.Color(149, 223, 237));
        Result.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/report_kwh_usage.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(77, 73));

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel25.setText("KWH Usage");

        tf_kwh_usage.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/Computer-Hardware-Print-icon.png"))); // NOI18N
        jLabel26.setText("Details");
        jLabel26.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel26AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        tf_income.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_income, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tf_kwh_usage, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_kwh_usage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(tf_income, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        Result.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 220, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/offices.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Units Sold");

        tf_units.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/Icon/Computer-Hardware-Print-icon.png"))); // NOI18N
        jLabel27.setText("Details");
        jLabel27.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel27AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(tf_units, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_units, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Result.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 220, 120));

        bg_layout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/bg_trans.png"))); // NOI18N
        Result.add(bg_layout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 620, 240));

        bg_Transaction2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_IMG/view_transparant.png"))); // NOI18N
        bg_Transaction2.setMaximumSize(new java.awt.Dimension(801, 514));
        bg_Transaction2.setMinimumSize(new java.awt.Dimension(801, 514));
        Result.add(bg_Transaction2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 1070, 513));
        Result.add(tf_income_tumbal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainFrame.add(Result, "card4");

        getContentPane().add(MainFrame, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 1071, 559);
    }// </editor-fold>//GEN-END:initComponents
    
    int x = 225;
    int z = 0;
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickMainMenu(JPanel h1, JPanel h2, int numberbool){
        if(numberbool == 1){
            h1.setBackground(new Color (57,121,255));
            h2.setBackground(new Color (56,94,245));
        }else {
            h1.setBackground(new Color (56,94,245));
            h2.setBackground(new Color (57,121,255));
        }
    }
    
    public void changeimage(JLabel button, String resourcheimg ){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    }
    
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
        if (dashboard == true){
            menushowhide.setPreferredSize(new Dimension(45, menushowhide.getHeight()));
            changeimage(button,"/Design_IMG/Icon/menu_32px.png");
            changecolor(jp_back, new Color(56,94,245));
        } else {
            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
            changeimage(button,"/Design_IMG/Icon/back_32px.png");
        }
    }
    
    protected void total_kwh(){
        String sql = "select sum(Used_KWH) as total_kwh from owner_detail_apart";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                    tf_kwh_usage.setText(hasil.getString("total_kwh"));
            }
        }catch (Exception e) {
            
        }
    }
    
    protected void total_income(){
        String sql = "select sum(Total) as total_income from report_kwh";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                     tf_income_tumbal.setText(hasil.getString("total_income"));
                     int total = Integer.parseInt(tf_income_tumbal.getText());
                     NumberFormat nf = NumberFormat.getInstance();
                     tf_income.setText("Rp. " +nf.format(total));
            }
        }catch (Exception e) {
            
        }
    }
    
    
    
    protected void animated(){
        if ( x == 225 ) {
            //MenuHide.setSize(0, MenuHide.getHeight());
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        for ( int i = 100; i >= 0; i--){
                            Thread.sleep(1);
                            MenuHide.setSize(i, MenuHide.getHeight());
                            z++;
                        }
                        changecolor(jp_back, new Color(56,94,245));
                        
                        changeimage(btn_Back,"/Design_IMG/Icon/menu_32px.png");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=0;
        }
    }
    
    protected void animated2nd(){
        if ( x == 225){
            MenuHide.setSize(0, MenuHide.getHeight());
        }else if (x== 0){
            MenuHide.setSize(0, MenuHide.getHeight());
        }
    }
    
    protected void lock_system(){
        btn_Back.setEnabled(false);
        MainMenu.setEnabled(false);
        MainFrame.setEnabled(false);
    }
    
    protected void kosong(){
        tf_nama.setText("");
        ta_alamat.setText("");
        tf_nohp.setText("");
        
    }
    
    protected void kosong_payment(){
        tf_id1.setText("");
        tf_nama1.setText("");
        tf_nohp1.setText("");
        tf_KWH.setText("");
        tf_used.setText("");
        tf_total.setText("");
    }
    
    protected void auto_number(){
        try {
            String sql="select * from owner_detail_apart order by Id_Number desc";
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            if (hasil.next()) {
                String auto = hasil.getString("Id_Number").substring(1);
                String AN = "" + (Integer.parseInt(auto) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "000";}
                else if(AN.length()==2)
                {Nol = "00";}
                else if(AN.length()==3)
                {Nol = "0";}
                else if(AN.length()==4)
                {Nol = "";}
                
               tf_id.setText("X" + Nol + AN);
            } else {
               tf_id.setText("X0001");
            }

           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
    }
    
    protected void Count_Payment_Update(){
        int a = Integer.parseInt(tf_KWH.getText());
        int b = Integer.parseInt(tf_used.getText());
        int kwh = 1467;
        int stotal;
        stotal = b * kwh;
        NumberFormat nf = NumberFormat.getInstance();
        tf_total.setText("Rp. " +nf.format(stotal));
    }
    
    protected void update_kwh(){
        int a = Integer.parseInt(tf_KWH.getText());
        int b = Integer.parseInt(tf_used.getText());
        int kwhbaru = a+ b;
        try {
            String sql = "update owner_detail_apart set Used_KWH='"+kwhbaru+"' where Id_Number='"+tf_id1.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.executeUpdate();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Total Saldo gagal diperbarui" +e);
        }
    }    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if (this.getExtendedState()!= Dashboard.MAXIMIZED_BOTH){
            this.setExtendedState(Dashboard.MAXIMIZED_BOTH);
        }else {
            this.setExtendedState(Dashboard.NORMAL);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        changecolor(btn_Max, new Color(25, 29, 74));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        changecolor(btn_Max, new Color(56,94,245));
    }//GEN-LAST:event_jLabel2MouseExited

    private void btn_SettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseClicked
        // TODO add your handling code here:
        dispose();
        new LoginAccess().setVisible(true);
    }//GEN-LAST:event_btn_SettingMouseClicked

    private void btn_SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseEntered
        // TODO add your handling code here:
        changecolor(line1, new Color(6,177, 150));
        animated();
    }//GEN-LAST:event_btn_SettingMouseEntered

    private void btn_SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseExited
        // TODO add your handling code here:
        changecolor(line1, new Color(56,94,245));
    }//GEN-LAST:event_btn_SettingMouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        changecolor(btn_Close, new Color(56,94,245));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btn_unitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_unitMouseClicked
        // TODO add your handling code here:
        if (evt.getSource()==btn_unit){
            Transaction_Apart.setVisible(true);
            changecolor(Template_1,new Color(102,255,204));
            changecolor(Template_2,new Color(204,204,204));
            changecolor(Template_3,new Color(204,204,204));
            Payment_System.setVisible(false);
            Result.setVisible(false);
            MainFrame_Home.setVisible(false);
        }
    }//GEN-LAST:event_btn_unitMouseClicked

    private void btn_PaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PaymentMouseClicked
        // TODO add your handling code here:
        if (evt.getSource()==btn_Payment){
            Transaction_Apart.setVisible(false);
            Payment_System.setVisible(true);
            changecolor(Template_2,new Color(102,255,204));
            changecolor(Template_1,new Color(204,204,204));
            changecolor(Template_3,new Color(204,204,204));
            Result.setVisible(false);
            MainFrame_Home.setVisible(false);
        }
    }//GEN-LAST:event_btn_PaymentMouseClicked

    private void btn_ResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ResultMouseClicked
        // TODO add your handling code here:
        if (evt.getSource()==btn_Result){
            Transaction_Apart.setVisible(false);
            Payment_System.setVisible(false);
            Result.setVisible(true);
            count();
            total_kwh();
            total_income();
            changecolor(Template_3,new Color(102,255,204));
            changecolor(Template_1,new Color(204,204,204));
            changecolor(Template_2,new Color(204,204,204));
            MainFrame_Home.setVisible(false);
            
        }
    }//GEN-LAST:event_btn_ResultMouseClicked

    private void Template_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Template_1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Template_1MouseEntered

    private void Template_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Template_1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Template_1MouseExited

    private void btn_unitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_unitMouseEntered
        // TODO add your handling code here:
        changecolor(Template_1,new Color(102,255,204));
        changecolor(Template_2,new Color(204,204,204));
        changecolor(Template_3,new Color(204,204,204));
    }//GEN-LAST:event_btn_unitMouseEntered

    private void btn_unitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_unitMouseExited
        // TODO add your handling code here:
        //changecolor(Template_1,new Color(204,204,204));
    }//GEN-LAST:event_btn_unitMouseExited

    private void btn_PaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PaymentMouseEntered
        // TODO add your handling code here:
        changecolor(Template_2,new Color(102,255,204));
        changecolor(Template_1,new Color(204,204,204));
        changecolor(Template_3,new Color(204,204,204));
    }//GEN-LAST:event_btn_PaymentMouseEntered

    private void btn_PaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PaymentMouseExited
        // TODO add your handling code here:
        //changecolor(Template_2,new Color(204,204,204));
    }//GEN-LAST:event_btn_PaymentMouseExited

    private void btn_ResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ResultMouseEntered
        // TODO add your handling code here:
        changecolor(Template_3,new Color(102,255,204));
        changecolor(Template_1,new Color(204,204,204));
        changecolor(Template_2,new Color(204,204,204));
    }//GEN-LAST:event_btn_ResultMouseEntered

    private void btn_ResultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ResultMouseExited
        // TODO add your handling code here:
        //changecolor(Template_3,new Color(204,204,204));
    }//GEN-LAST:event_btn_ResultMouseExited

    private void btn_BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseExited
        // TODO add your handling code here:
        changecolor(line, new Color(56,94,245));
        if (x==225){
            MenuHide.setSize(225, MenuHide.getHeight());
        }
    }//GEN-LAST:event_btn_BackMouseExited

    private void btn_BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseEntered
        // TODO add your handling code here:
        if ( x == 225 ) {
            MenuHide.setSize(225, MenuHide.getHeight());
            MainFrame_Home.setVisible(true);
            Transaction_Apart.setVisible(false);
            Payment_System.setVisible(false);
            Result.setVisible(false);
            changecolor(Template_1,new Color(204,204,204));
            changecolor(Template_2,new Color(204,204,204));
            changecolor(Template_3,new Color(204,204,204));
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        for ( int i = 225; i >= 0; i--){
                            Thread.sleep(1);
                            MenuHide.setSize(i, MenuHide.getHeight());
                            z++;
                        }
                        changecolor(jp_back, new Color(56,94,245));
                        changeimage(btn_Back,"/Design_IMG/Icon/menu_32px.png");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=0;
        } else if( x == 0 ){
            MenuHide.setSize(x, MenuHide.getHeight());
            changecolor(Template_1,new Color(204,204,204));
            changecolor(Template_2,new Color(204,204,204));
            changecolor(Template_3,new Color(204,204,204));
            Thread th = new Thread(){
                @Override
                public void run(){
                    try {
                        for (int i = 0; i <= x; i++){
                            Thread.sleep(1);
                            MenuHide.setSize(i, MenuHide.getHeight());
                        }
                        changecolor(jp_back, new Color(57,121,255));
                        changeimage(btn_Back,"/Design_IMG/Icon/back_32px.png");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x = 225;
        }
        changecolor(line, new Color(247, 78, 105));
    }//GEN-LAST:event_btn_BackMouseEntered

    private void btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseClicked
        // TODO add your handling code here:

        /*clickMainMenu(jp_back,jp_setting,1);
        //buat method hide and show menu
        if (a==true){
            hideshow(MainMenu,a, btn_Back);
            SwingUtilities.updateComponentTreeUI(this);
            a=false;
        }else{
            hideshow(MainMenu,a, btn_Back);
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }*/
    }//GEN-LAST:event_btn_BackMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        changecolor(layout1,new Color(102,255,204));
        changecolor(jp_Detail_1,new Color(102,255,204));
        detailConcept.setText("WE AIM TO CREATE THE BEAUTY, ABUNDANCE, AND IMMUTABLE VALUE OF WATER.");
        
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        changecolor(layout1,new Color(222,222,222));
        changecolor(jp_Detail_1,new Color(222,222,222));
        detailConcept.setText("");
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        changecolor(layout2,new Color(51,51,255));
        changecolor(jp_Detail_1,new Color(51,51,255));
        detailConcept.setText("BLENDING WITH THE SURROUNDINGS TO BECOME A WATER GARDEN PALACE.");
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        changecolor(layout2,new Color(222,222,222));
        changecolor(jp_Detail_1,new Color(222,222,222));
        detailConcept.setText("");
    }//GEN-LAST:event_jLabel10MouseExited

    private void MenuHide_TemplateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHide_TemplateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuHide_TemplateMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "insert into owner_detail_apart (Id_Number,Name,Address,No_Handphone,RP_Tower,RP_Bed,RP_Unit_Style,Used_KWH) values (?,?,?,?,?,?,?,'0');";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tf_id.getText());
            stat.setString(2, tf_nama.getText());//
            stat.setString(3, ta_alamat.getText());
            stat.setString(4, tf_nohp.getText());
            stat.setString(5, (String) cb_Tower.getSelectedItem());
            stat.setString(6, (String) cb_BadType.getSelectedItem());
            stat.setString(7, (String) cb_UnitStyle.getSelectedItem());
            if ((tf_nama.getText().equals("")) &&(ta_alamat.getText().equals(""))){
                tf_nama.requestFocus();
                ta_alamat.requestFocus();
            }else if (tf_nohp.getText().equals("")){
                tf_nohp.requestFocus();
            }else {
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data telah tersimpan");
                kosong();
                auto_number();
            }
            
            //new FormLoginUtama().setVisible(true);
            //tfregist_user.requestFocus();
            //dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan " + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_id1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_id1KeyReleased
        // TODO add your handling code here:
        try {
            String sql = "select Name,No_Handphone,Used_KWH from owner_detail_apart where Id_Number = '" + tf_id1.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String snama = hasil.getString("Name");
                String snohp = hasil.getString("No_Handphone");
                String skwh = hasil.getString("Used_KWH");
                tf_nama1.setText(snama);
                tf_nohp1.setText(snohp);
                tf_KWH.setText(skwh);
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_tf_id1KeyReleased

    private void tf_id1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_id1KeyPressed
        // TODO add your handling code here:
        try {
            String sql = "select Name,No_Handphone,Used_KWH from owner_detail_apart where Id_Number = '" + tf_id1.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String snama = hasil.getString("Name");
                String snohp = hasil.getString("No_Handphone");
                String skwh = hasil.getString("Used_KWH");
                tf_nama1.setText(snama);
                tf_nohp1.setText(snohp);
                tf_KWH.setText(skwh);
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_tf_id1KeyPressed

    private void tf_usedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_usedKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usedKeyPressed

    private void tf_usedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_usedKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usedKeyReleased

    private void tf_usedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usedActionPerformed
        // TODO add your handling code here:
        Count_Payment_Update();
    }//GEN-LAST:event_tf_usedActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sql = "insert into report_kwh (Id_Number,Name,No_Handphone,Usage_KWH,Total)values (?,?,?,?,?);";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tf_id1.getText());
            stat.setString(2, tf_nama1.getText());//
            stat.setString(3, tf_nohp1.getText());
            stat.setString(4, tf_used.getText());
            int a = Integer.parseInt(tf_KWH.getText());
            int b = Integer.parseInt(tf_used.getText());
            int kwh = 1467;
            int stotal;
            stotal = b * kwh;
            String fix = Integer.toString(stotal);
            stat.setString(5, fix);
            stat.executeUpdate();
            update_kwh();
            JOptionPane.showMessageDialog(null, "Tagihan telah terbayar");
            kosong_payment();
            //new FormLoginUtama().setVisible(true);
            //tfregist_user.requestFocus();
            //dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pembayaran gagal disimpan " + e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel27AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel27AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27AncestorAdded

    private void jLabel26AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel26AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26AncestorAdded

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
                Map hash= new HashMap();           
           try {
               InputStream is = getClass().getResourceAsStream("/Report/report_owner_apart.jrxml");
            File file=new File("src/Report/report_owner_apart.jrxml");
            jasdes=JRXmlLoader.load(is);
            jasrep=JasperCompileManager.compileReport(jasdes);
            jaspri=JasperFillManager.fillReport(jasrep,hash,conn);
            JasperViewer.viewReport(jaspri,false);
            
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        Map hash= new HashMap();           
           try {
               InputStream is = getClass().getResourceAsStream("/Report/report_kwh_usage.jrxml");
            File file=new File("src/Report/report_kwh_usage.jrxml");
            jasdes=JRXmlLoader.load(is);
            jasrep=JasperCompileManager.compileReport(jasdes);
            jaspri=JasperFillManager.fillReport(jasrep,hash,conn);
            JasperViewer.viewReport(jaspri,false);
            
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel26MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel IkonWindow;
    private javax.swing.JPanel MainFrame;
    private javax.swing.JPanel MainFrame_Home;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel MenuHide;
    private javax.swing.JPanel MenuHide_Template;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JPanel Payment_System;
    private javax.swing.JPanel Result;
    private javax.swing.JPanel Template_1;
    private javax.swing.JPanel Template_2;
    private javax.swing.JPanel Template_3;
    private javax.swing.JPanel Transaction_Apart;
    private javax.swing.JLabel bg_MainFrame_Home;
    private javax.swing.JLabel bg_MainMenu;
    private javax.swing.JLabel bg_Transaction;
    private javax.swing.JLabel bg_Transaction1;
    private javax.swing.JLabel bg_Transaction2;
    private javax.swing.JLabel bg_layout;
    private javax.swing.JLabel bg_layout1;
    private javax.swing.JLabel bg_layout2;
    private javax.swing.JLabel branding;
    private javax.swing.JLabel branding1;
    private javax.swing.JLabel btn_Back;
    private javax.swing.JPanel btn_Close;
    private javax.swing.JPanel btn_Max;
    private javax.swing.JPanel btn_Min;
    private javax.swing.JLabel btn_Payment;
    private javax.swing.JLabel btn_Result;
    private javax.swing.JLabel btn_Setting;
    private javax.swing.JLabel btn_unit;
    private javax.swing.JComboBox<String> cb_BadType;
    private javax.swing.JComboBox<String> cb_Tower;
    private javax.swing.JComboBox<String> cb_UnitStyle;
    private javax.swing.JLabel detail;
    private javax.swing.JLabel detailConcept;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_Detail_1;
    private javax.swing.JPanel jp_Detail_2;
    private javax.swing.JPanel jp_back;
    private javax.swing.JPanel jp_setting;
    private javax.swing.JPanel layout1;
    private javax.swing.JPanel layout2;
    private javax.swing.JPanel line;
    private javax.swing.JPanel line1;
    private javax.swing.JTextArea ta_alamat;
    private javax.swing.JTextField tf_KWH;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_id1;
    private javax.swing.JLabel tf_income;
    private javax.swing.JLabel tf_income_tumbal;
    private javax.swing.JLabel tf_kwh_usage;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_nama1;
    private javax.swing.JTextField tf_nohp;
    private javax.swing.JTextField tf_nohp1;
    private javax.swing.JTextField tf_total;
    private javax.swing.JLabel tf_units;
    private javax.swing.JTextField tf_used;
    // End of variables declaration//GEN-END:variables

    
    
}
